version: 2.1

orbs:
  codecov: codecov/codecov@1.0.2

jobs:
  run_tests:
    docker:
      - image: cimg/python:3.8.2
    steps:
      - checkout
      - run:
          name: Install Python Dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip3 install -r handlers/requirements.txt
      - run:
          name: Build AWS  Serverless Application Model
          command:  |
            . venv/bin/activate
            pip list
            sam build
      - run:
          name: Run Unit Tests 
          command: |
            . venv/bin/activate
            python -m pytest --cov=tests/unit --cov-report=xml  
            mkdir coverage
            mv ./coverage.xml ./coverage/
      - codecov/upload:
          file: './coverage/coverage.xml'
          token: $CODECOV_TOKEN
      - store_artifacts:
          path: test-reports    

workflows:
  build_test:
    jobs:
      - run_tests
